### ISSUE TITLE
Add Latest Homepage screenshot in the README.md

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#17]
After Fixing the issue, tag the issue by #<issuenumber> in your Pull request like below example.
`Added Admin Login Page fixing issue no #1 .`

Find the `teslaclublive.png` in the root folder and replace it with the latest cropped screenshot of the home page having same name to update the image in the `README.md`.

[teslaclublive.png](https://github.com/SudhansuuRanjan/tesla-nitp-web/blob/main/teslaclublive.png)

**Comment by suraj-markup** [comment]
yes sir
