### ISSUE TITLE
Update Admin Navbar

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#18]
After Fixing the issue tag the issue by #<Issue Number> in your Pull request like below example.
Added Admin Login Page fixing issue no #1 .

Find the `src/admin/components/NavBar.jsx` component 

Update the previous Navbar links to,
- About -> Gallery ('/admin/gallery')
- Events -> Events('/admin/events')
- News -> Blogs('/admin/blogs')
- Projects -> Projects('/admin/projects')
- Team -> Team('/admin/team')
- Gallery -> Profile('/admin/profile')

for both desktop and mobile screen.

**Comment by lipi150** [comment]
Update navbar
