### ISSUE TITLE
Design Admin Footer Component

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#19]
After Fixing the issue tag the issue by #<IssueNo> in your Pull request like below example.
Added Admin Login Page fixing issue no https://github.com/SudhansuuRanjan/tesla-nitp-web/pull/1 .

Find the `src/admin/components/Footer.jsx` component.

Design the Admin footer to match the below UI and also it should be fully responsive.<br/>
![Screenshot (1382)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/b1217cb1-f40c-4a67-bafd-ffabab2a8b71)

**Comment by Sky-De** [comment]
Would you mind if i ask clarify this issue?
Do you want new component in footer folder with name AdminFooter.jsx or just new component in same file of older footer or even just part of code which added to existing footer?
I took a look to your footer code
seems it has implemented same thing already

**Comment by suraj-markup** [comment]
doing it.

**Comment by RituRaj30** [comment]
I want to give a try solving this issue.

**Comment by SudhansuuRanjan** [comment]
@Sky-De We need a simpler footer component for admin section (as in the attached image) so, Just modify the `src/admin/components/Footer.jsx` no need to create a new file.

**Comment by SudhansuuRanjan** [comment]
Assigning this issue to all three, Best of the three will be merged.
