### ISSUE TITLE
Design an Admin profile component

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#21]
After Fixing the issue tag the issue by #<IssueNo> in your Pull request like below example.
Added Admin Login Page fixing issue no https://github.com/SudhansuuRanjan/tesla-nitp-web/pull/1 .

Find the `src/admin/pages/profile/Profile.jsx` component.

Design the profile Component to match the below UI and also it should be fully responsive.<br/>
![Screenshot (1383)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/84f3ea08-8c5d-40a7-90eb-34b43e8141d5)

**Comment by sonuschauhan** [comment]
yes sir
