### ISSUE TITLE
Improve Admin dashboard Panel

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#22]
After Fixing the issue tag the issue by #<IssueNo> in your Pull request like below example.
Added Admin Login Page fixing issue no https://github.com/SudhansuuRanjan/tesla-nitp-web/pull/1 .

Find the `src/admin/pages/dasboard/Dashboard.jsx` component.

Design the Dashboard components and to appropriate linking to match the below UI and also try to make it fully responsive.<br/>
![Admin Dashboard](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/e9c622c8-5f58-487c-8fe2-f8383ae18ea6)

**Comment by sakshi025** [comment]
@SudhansuuRanjan Assign this issue to me.
