### ISSUE TITLE
[BUG] :  Buttons do not have an accessible name

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#44]
**Describe the bug**

Buttons do not have an accessible name

**To Reproduce**
1. Open website 
2. Open dev tools 
3. Click on lighthouse
4. Measure lighthouse score
5. See accessibility error

**Expected behavior**
All the buttons should have an accessible names.

**Screenshots**
![Screenshot (1470)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/11595a2a-e50f-4a47-9019-5e5e23c08e5f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Additional context**
You can refer to the following [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) for more info on accessible buttons.

**Comment by vaishnavibn14** [comment]
Could you please assign me this issue

**Comment by SudhansuuRanjan** [comment]
Proceed with it.
