### ISSUE TITLE
[BUG] : The `img` elements do not have `height` and `width` attributes.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#45]
**Describe the bug**
The `img` elements do not have `height` and `width` attributes.

**To Reproduce**
1. Open website
2. Open dev tools
3. Click on lighthouse
4. Measure lighthouse score
5. See accessibility error

**Expected behavior**
All the `img` elements  must have `height` and `width` attributes.

**Screenshots**

![Screenshot (1471)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/ae58417e-f57f-4612-a52d-3d0951b01e83)

**Desktop (please complete the following information):**
OS: Windows
Browser : Chrome

**Additional context**
You can refer to the following [docs](https://www.w3schools.com/tags/tag_img.asp) for more info on img attributes.

**Comment by pranav-jadhav** [comment]
I would like to work on this issue

**Comment by SudhansuuRanjan** [comment]
Go for it.

**Comment by BuiHuyTam** [comment]
I want to join this issue

**Comment by SudhansuuRanjan** [comment]
Hey @BuiHuyTam , @pranav-jadhav is already working on this issue, please check another issue if available or create your own to work on it. Happy Coding!
