### ISSUE TITLE
[BUG] : Background and foreground colors do not have a sufficient contrast ratio.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#50]
###  Describe the bug
`Background and foreground colors do not have a sufficient contrast ratio.` Fix this accessibility bug without changing the website theme. Only use Tailwind CSS for styling and also do not use global styling for this project. 

### To Reproduce

1. Open website
2. Open dev tools
3. Click on lighthouse
4. Measure lighthouse score
5. See accessibility errors - `Background and foreground colors do not have a sufficient contrast ratio.`

### Expected behavior 
No contrast Errors

### Screenshots
![Screenshot (1477)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/385df1ac-4bde-4be7-8482-ab1dbfc8d52f)

### Desktop (please complete the following information):
OS: Windows
Browser : Chrome

### Additional context
You can refer to the following [docs](https://tailwindcss.com/docs/text-color) for more info on tailwind text colors.

**Comment by Sn4pe** [comment]
Hello, could you assign me this issue?

**Comment by suraj-markup** [comment]
Please @SudhansuuRanjan sir assign it to me.

**Comment by SudhansuuRanjan** [comment]
Go ahead.
