### ISSUE TITLE
[BUG] : Fix currently opened FAQ to one at a time.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#56]
**Describe the bug**
When you expand a specific FAQ, all other FAQs should automatically close (i.e., only one FAQ should be open at a time), and the first one should be open by default as the starting point.

**To Reproduce**
1. Go to https://tesla-nitp.vercel.app/
2. Scroll down to FAQ section

**Expected behavior**
When you expand a specific FAQ, all other FAQs should automatically close (i.e., only one FAQ should be open at a time), and the first one should be open by default as the starting point.

**Screenshots**
![Screenshot (1478)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/c20fd8dd-f44d-4c1f-9c98-44a63ac42123)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome

**Additional context**
You can use a global state to store the currently opened FAQ id and the default value can be the id of the first one.

**Comment by tsongtheng** [comment]
Hey @SudhansuuRanjan , let me try this. Please assign me.

**Comment by SudhansuuRanjan** [comment]
Go for it!

**Comment by SudhansuuRanjan** [comment]
Hey @tsongtheng what's the update?

**Comment by tsongtheng** [comment]
Hey @SudhansuuRanjan, something came up. I won't be able to work on the issue. Can you assign to someone else?
I will be working on some other issue in the future.

**Comment by buneeIsSlo** [comment]
Hey @SudhansuuRanjan, I got this.

**Comment by SudhansuuRanjan** [comment]
Go ahead!
