### ISSUE TITLE
[BUG] : On clicking outside the Navbar Modal on small screens, the Modal should close.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [SudhansuuRanjan/tesla-nitp-web#57]
**Describe the bug**
On clicking outside the Navbar Modal on small screens, the Modal should close.

**To Reproduce**
1. Go to https://tesla-nitp.vercel.app/
2. Make the width of the screen below 600px
3. Click on the Nav Menu button
4. See the bug

**Current behavior**
Currently it closes only if we press cancel button.

**Screenshots**
![Screenshot (1479)](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/77230416/48615ddf-7f6e-4202-947e-9af9f4446e6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by y-ashaswini** [comment]
Greetings! I've worked on full-stack web dev related projects, mainly built on and around JavaScript libraries. I've worked on such an issue earlier. Could I take this up?

**Comment by SudhansuuRanjan** [comment]
Proceed with it.

**Comment by SudhansuuRanjan** [comment]
Hey @y-ashaswini , I think you will not need the credentials for fixing this issue.
