### ISSUE TITLE
[Feature] : Show real event images in Our Gallery section on Home Page

### ISSUE THREAD

**Issue by thesohailjafri** [SudhansuuRanjan/tesla-nitp-web#60]
**Issue Description:**
Currently, Our Gallery on Home pages use placeholder images but we can use images from photo gallery since there are actual event images and have a high quality compared to placeholder image

**Current Behavior:**

![image](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/66732877/37d27e36-b617-4b74-9ecc-19e028228229)

**Steps to Reproduce:**
- Visit https://tesla-nitp.vercel.app/
- Scroll down to Our Gallery

**Describe alternatives you've considered**
We could use images from https://tesla-nitp.vercel.app/gallery

![image](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/66732877/3b1771bc-af66-4074-9e47-976f965acfe0)

**Possible Solution:**
Chose 4 images from https://tesla-nitp.vercel.app/gallery and add them in place of current Home Page - Our Gallery section images

**Comment by thesohailjafri** [comment]
Hi @SudhansuuRanjan Assign this to me

**Comment by SudhansuuRanjan** [comment]
Hey @thesohailjafri , we are using `appwrite cloud` to store/retrieve our images and also using `react-query` for querying the data, You need to implement the same in the Gallery component on Home Screen and map first 10-12 images in it.

**Comment by thesohailjafri** [comment]
Do let me know the refresh time for fetching latest data

**Comment by SudhansuuRanjan** [comment]
Great, Proceed with it then.

**Comment by thesohailjafri** [comment]
Hii @SudhansuuRanjan Could you add **hacktoberfest-accepted** label to his issue? That would be great.

Thank you for considering this request!
