### ISSUE TITLE
[BUG] : Displays Image with Incorrect ratio

### ISSUE THREAD

**Issue by suraj-markup** [SudhansuuRanjan/tesla-nitp-web#61]
**Describe the bug**
Displays Images with Incorrect ratio.

**To Reproduce**
1.Open website
2.Open dev tools
3.Click on lighthouse
4.Measure lighthouse score
5.See accessibility error

**Expected behavior**
Image display dimensions should match natural aspect ratio.

**Screenshots**
![image](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/96483690/2ea0dfcd-1311-442b-8455-ecaf40fadb18)

Desktop (please complete the following information):
OS: Windows
Browser : Chrome

Additional context
You can refer to the following [docs](https://www.w3schools.com/tags/tag_img.asp) for more info on img attributes.

**Additional context**
Solving this issue will help in increasing the score of Best Practices.

**Comment by suraj-markup** [comment]
@SudhansuuRanjan sir please assign me this.

**Comment by SudhansuuRanjan** [comment]
Go ahead!
