### ISSUE TITLE
[BUG] : On Clicking outside Gallery Popup, Popup should close. And also image should change using the left and right buttons

### ISSUE THREAD

**Issue by suraj-markup** [SudhansuuRanjan/tesla-nitp-web#62]
**Describe the bug**
On Clicking outside Gallery Popup, Popup should close. And also image should change using the left and right buttons

**To Reproduce**
1. Go to  [website](https://tesla-nitp.vercel.app/).
2. Click on gallery 
3. Click on any Image.
4. Now the Image popup should close if you click outside the popup.
5. And image should change using the left or right buttons of keyboard.

**Current behavior**
It does not closes if we click outside the popup.

**Screenshots**
![image](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/96483690/17c006b6-17ea-4c3e-bce5-87f7c7d1a0a8)

Desktop (please complete the following information):

OS: Windows
Browser: Chrome

**Comment by suraj-markup** [comment]
@SudhansuuRanjan sir please assign it to me .

**Comment by SudhansuuRanjan** [comment]
> @SudhansuuRanjan sir please assign it to me .

Go for it.
