### ISSUE TITLE
[BUG] : Heading elements are not in a sequentially-descending order

### ISSUE THREAD

**Issue by Deflecting-Torque** [SudhansuuRanjan/tesla-nitp-web#69]
**Describe the bug**
-Heading elements are not in a sequentially-descending order. 
-If we resolve this issue then it will increase the Accessibility score to 100 in Lighthouse tool.

**To Reproduce**
1. Go to 'https://tesla-nitp.vercel.app/'
2. Click on 'Inspect'
3. Go to 'Lighthouse'
4. See error which is named : Heading elements are not in a sequentially-descending order

**Expected behavior**
- There should be no error of this type.

**Screenshots**
![image](https://github.com/SudhansuuRanjan/tesla-nitp-web/assets/116160070/93e417dc-34bf-4728-b32e-a83ad975420f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by Deflecting-Torque** [comment]
sir please assign me this issue.

**Comment by SudhansuuRanjan** [comment]
Go on.
